kind: DaemonSet
image:
  repository: fluent/fluent-bit
  tag: "2.0"
  pullPolicy: IfNotPresent

replicaCount: 1

config:
  service: |
    [SERVICE]
      Flush 1
      Daemon  Off
      Log_Level info
      Parsers_File parsers.conf
      HTTP_Server On
      HTTP_Listen 0.0.0.0
      HTTP_Port 2020
      Health_Check On
      storage.path /var/log/flb-storage/

  inputs: |
    [INPUT]
      Name tail
      Tag kube.*
      Path /var/log/containers/*.log
      # multiline.parser docker, cri
      Parser docker
      Mem_Buf_Limit 5MB
      Skip_Long_Lines On
      DB /var/log/flb_kube.db
      Refresh_Interval 10

  filters: |
    [FILTER]:
      Name  kubernetes
      Match kube.*
      Merge_Log On
      Keep_Log Off
      K8S-Logging.Parser On
      K8S-Logging.Exclude On

  outputs: |
    [OUTPUT]
      Name http 
      Match kube.*
      Host logstash-logstash
      Port 5044
      Format json
